---
- hosts: hadoop nfsgw
  remote_user: root
  tasks:
    - copy: 
        src: core-site.xml.nfs
        dest: /usr/local/hadoop/etc/hadoop/core-site.xml
    - copy: 
        src: hdfs-site.xml
        dest: /usr/local/hadoop/etc/hadoop/
    - copy: 
        src: slaves
        dest: /usr/local/hadoop/etc/hadoop/
    - copy: 
        src: yarn-site.xml 
        dest: /usr/local/hadoop/etc/hadoop/
    - copy: 
        src: mapred-site.xml
        dest: /usr/local/hadoop/etc/hadoop/
    - shell : chown  -R 0.0  /usr/local/hadoop
